INSERT [DrDoolittleVet].[dbo].[VetRoster] ([VetID], [roster1], [roster2], [roster3], [roster4], [roster5], [roster6], [roster7])
VALUES (2, 1, 1, 1, 0, 0, 0, 1)
INSERT [DrDoolittleVet].[dbo].[VetRoster] ([VetID], [roster1], [roster2], [roster3], [roster4], [roster5], [roster6], [roster7])
VALUES (3, 0, 0, 1, 1, 1, 1, 0)
INSERT [DrDoolittleVet].[dbo].[VetRoster] ([VetID], [roster1], [roster2], [roster3], [roster4], [roster5], [roster6], [roster7])
VALUES (4, 0, 1, 0, 1, 0, 1, 1)													  
INSERT [DrDoolittleVet].[dbo].[VetRoster] ([VetID], [roster1], [roster2], [roster3], [roster4], [roster5], [roster6], [roster7])
VALUES (5, 1, 1, 0, 0, 1, 0, 1)