INSERT [DrDoolittleVet].[dbo].[PetOwners] ([FirstName], [LastName], [Address1], [Address2], [State], [PostCode], [PhoneNumber], [EmailAddress], [ProofType], [ProofNumber])
VALUES ('Andrew', 'Smith', '98 Glenside Ave', 'Craigie', 'WA', 6027, '043 632 1406', 'andy@coolguy.com', 'Mastercard', '5985456914789320')
INSERT [DrDoolittleVet].[dbo].[PetOwners] ([FirstName], [LastName], [Address1], [Address2], [State], [PostCode], [PhoneNumber], [EmailAddress], [ProofType], [ProofNumber])
VALUES ('Darren', 'Harris', '17 Bossman Cres', 'Woodvale', 'WA', 6025, '045 175 1256', 'dazza66@hotmail.com', 'Visa', '3905301278362029')
INSERT [DrDoolittleVet].[dbo].[PetOwners] ([FirstName], [LastName], [Address1], [Address2], [State], [PostCode], [PhoneNumber], [EmailAddress], [ProofType], [ProofNumber]) 
VALUES ('Martin', 'Fredericks',  '63 Supervisor St', 'Whiteman', 'WA', 6034, '045 223 3090', 'stretch@bigpond.com', 'Drivers Licence', '5541206')
INSERT [DrDoolittleVet].[dbo].[PetOwners] ([FirstName], [LastName], [Address1], [Address2], [State], [PostCode], [PhoneNumber], [EmailAddress], [ProofType], [ProofNumber]) 
VALUES ('James', 'Hetfield', '53 Rockgod Blvd', 'Bullridge', 'CO', 20015, '014 156 7067', 'rockgod@metallica.com', 'Passport', 'J67891145H')
INSERT [DrDoolittleVet].[dbo].[PetOwners] ([FirstName], [LastName], [Address1], [Address2], [State], [PostCode], [PhoneNumber], [EmailAddress], [ProofType], [ProofNumber]) 
VALUES ('William', 'Rose', '69 Gunnar Rd', 'Spencer', 'TX', 36114, '017 409 0845', 'axl@arpnet.com', 'American Express', '009845236754371421')
INSERT [DrDoolittleVet].[dbo].[PetOwners] ([FirstName], [LastName], [Address1], [Address2], [State], [PostCode], [PhoneNumber], [EmailAddress], [ProofType], [ProofNumber])
VALUES ('Steve', 'Foreman', '44 Crikey Way', 'Townsville', 'QLD', 4575, '044 439 2321', 'croc11@hotmail.com', 'Passport', 'S43350071H')
INSERT [DrDoolittleVet].[dbo].[PetOwners] ([FirstName], [LastName], [Address1], [Address2], [State], [PostCode], [PhoneNumber], [EmailAddress], [ProofType], [ProofNumber])
VALUES ('Warren', 'Terrar', '18a Doomsdae Rd', 'Birdsville', 'QLD', 4708, '041 392 4041', 'rlaruakbr@bigpond.com', 'Green Card', 'US784GH64')
