INSERT [DrDoolittleVet].[dbo].[Appointments] ([PetID], [VetID], [AppointDate], [AppointTime], [AppointPrice], [AppointComment])
VALUES (4, 3, '2020-09-24', '10:30', 0, 'Neutering')
INSERT [DrDoolittleVet].[dbo].[Appointments] ([PetID], [VetID], [AppointDate], [AppointTime], [AppointPrice], [AppointComment])
VALUES (6, 5, '2020-09-24', '08:45', 0, 'Annual check-up')
INSERT [DrDoolittleVet].[dbo].[Appointments] ([PetID], [VetID], [AppointDate], [AppointTime], [AppointPrice], [AppointComment])
VALUES (1, 3, '2020-09-24', '08:15', 0, 'Swallowed something poisonous')
INSERT [DrDoolittleVet].[dbo].[Appointments] ([PetID], [VetID], [AppointDate], [AppointTime], [AppointPrice], [AppointComment])
VALUES (3, 4, '2020-09-25', '09:45', 0, 'Surgery to remove cyst')
INSERT [DrDoolittleVet].[dbo].[Appointments] ([PetID], [VetID], [AppointDate], [AppointTime], [AppointPrice], [AppointComment])
VALUES (2, 3, '2020-09-24', '11:00', 0, 'Bee-sting on nose')
INSERT [DrDoolittleVet].[dbo].[Appointments] ([PetID], [VetID], [AppointDate], [AppointTime], [AppointPrice], [AppointComment])
VALUES (9, 3, '2020-09-25', '10:45', 0, 'Kennel cough')
INSERT [DrDoolittleVet].[dbo].[Appointments] ([PetID], [VetID], [AppointDate], [AppointTime], [AppointPrice], [AppointComment])
VALUES (10, 4, '2020-09-25', '08:30', 0, 'Annual check-up')
INSERT [DrDoolittleVet].[dbo].[Appointments] ([PetID], [VetID], [AppointDate], [AppointTime], [AppointPrice], [AppointComment])
VALUES (8, 3, '2020-09-25', '10:15', 0, 'Will not eat food')
INSERT [DrDoolittleVet].[dbo].[Appointments] ([PetID], [VetID], [AppointDate], [AppointTime], [AppointPrice], [AppointComment])
VALUES (11, 2, '2020-09-26', '10:00', 0, 'Dew-claw removal')
INSERT [DrDoolittleVet].[dbo].[Appointments] ([PetID], [VetID], [AppointDate], [AppointTime], [AppointPrice], [AppointComment])
VALUES (7, 2, '2020-09-26', '11:00', 0, 'Needs wings clipped')
